CMT_tag=$(tag)
CMTROOT=/data45/software/GlastExternals//CMT/v1r16p20040701
CMT_root=/data45/software/GlastExternals//CMT/v1r16p20040701
CMTVERSION=v1r16p20040701
CMTrelease=15
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/data41/users/tosti/glast/InstallArea/rh9_gcc32/bin:/data45/software/ScienceTools/v8r0p4/InstallArea/rh9_gcc32/bin:/data41/users/tosti/users/tosti/InstallArea/rh9_gcc32/bin:/data41/users/tosti/glast/users/tosti/InstallArea/rh9_gcc32/bin:/data45/software/GlastExternals//CMT/v1r16p20040701/${CMTBIN}:/data45/software/XMMSAS/xmmsas_20050815_1803/binextra:/data45/software/XMMSAS/xmmsas_20050815_1803/bin:/data45/software/XMMSAS/xmmsas_20050815_1803/bin/devel:/data45/software/heasoft/i686-pc-linux-gnu-libc2.2.4/bin:/data45/software/ScienceTools/v9/python/bin/:/usr/local/ruby-1.8.4/bin:/usr/java/j2sdk1.4.2_08/bin:/opt/lcg/bin:/usr/kerberos/bin:/opt/globus/bin:/opt/globus/sbin:/opt/edg/bin:/usr/local/bin:/usr/sue/bin:/bin:/usr/bin:/usr/X11R6/bin:/opt/glite/bin:/opt/glite/externals/bin:/opt/gpt/sbin:/opt/d-cache/srm/bin:/opt/d-cache/dcap/bin:.:/opt/edg/sbin:/data45/software/GlastExternals/ROOT/v5.14.00d/root/bin:/data45/software/bin:/data45/software/ScienceTools/v9/bin:/home/tosti/bin:/data45/software/bin:/data45/software/ScienceTools/v9/bin:/data45/software/GlastExternals/ROOT/v5.14.00d/root/bin:/data45/software/grace/bin:/data45/software/XMMSAS/xmmsas_20050815_1803/bin:/data45/software/lib/python2.4:/data45/software/star/bin:/data45/software/eclipse/bin:/data45/software/GlastExternals/ROOT/v5.14.00d/root/bin:/data45/software/bin:/data45/software/ScienceTools/v9/bin
CLASSPATH=/data41/users/tosti/glast/InstallArea/share/bin:/data41/users/tosti/glast/InstallArea/share/lib:/data45/software/ScienceTools/v8r0p4/InstallArea/share/bin:/data45/software/ScienceTools/v8r0p4/InstallArea/share/lib:/data41/users/tosti/users/tosti/InstallArea/share/bin:/data41/users/tosti/users/tosti/InstallArea/share/lib:/data41/users/tosti/glast/users/tosti/InstallArea/share/bin:/data41/users/tosti/glast/users/tosti/InstallArea/share/lib:/data45/software/GlastExternals//CMT/v1r16p20040701/java
debug_option=-g
cc=gcc
pp_cflags=-Di586
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=c++
cppflags=-pipe -ansi -pedantic -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplink=$(cpp) $(cpplinkflags) $(cppdebugflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=flex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar r
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
build_library_links=$(cmtexe) build library_links -quiet -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -quiet -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -quiet -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
implied_library_prefix=-l
SHELL=/bin/sh
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
lock_command=chmod -R a-w ../*
unlock_command=chmod -R g+w ../*
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=cp 
uninstall_command=/bin/rm -f 
cmt_installarea_command=ln -s 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=i686-unknown00-gcc32
fflare_tag=$(tag)
FFLAREROOT=/misc/data41/users/tosti/glast/ASP/fflare/v0
fflare_root=/misc/data41/users/tosti/glast/ASP/fflare/v0
FFLAREVERSION=v0
fflare_cmtpath=/data41/users/tosti/glast
fflare_offset=misc/ASP
fflare_project=Project1
AspPolicy_tag=$(tag)
ASPPOLICYROOT=/data41/users/tosti/glast/ASP/AspPolicy/v0r1
AspPolicy_root=/data41/users/tosti/glast/ASP/AspPolicy/v0r1
ASPPOLICYVERSION=v0r1
AspPolicy_cmtpath=/data41/users/tosti/glast
AspPolicy_offset=ASP
AspPolicy_project=Project1
PYTHONPATH=/opt/lcg/lib:/opt/lcg/lib/python:/opt/edg/lib:/opt/edg/lib/python:/opt/glite/lib/python:/data45/software/lib/python2.4/site-packages/HippoDraw:/data45/software/python_extras/numarray-1.4.1/Lib:/data45/software/python_extras/Numeric-24.2/Lib:/data45/software/python_extras/matplotlib-0.90.1:/data45/software/python_extras/matplotlib-0.90.1/lib:/data45/software/python_extras/pyfits-1.0.1/lib:/data45/software/GlastExternals/ROOT/v5.14.00d/root/lib:/data41/users/tosti/glast/ASP/AspPolicy/v0r1/python:/misc/data41/users/tosti/glast/ASP/fflare/v0/python:/misc/data41/users/tosti/glast/ASP/fflare/v0/${BINDIR}
CMTINSTALLAREA=/data41/users/tosti/glast/InstallArea
tag=rh9_gcc32
package=fflare
version=v0
PACKAGE_ROOT=$(FFLAREROOT)
srcdir=../src
bin=../$(fflare_tag)/
javabin=../classes/
mgrdir=cmt
project=Project1
use_requirements=requirements $(CMTROOT)/mgr/requirements $(ASPPOLICYROOT)/cmt/requirements 
use_includes= $(ppcmd)"$(AspPolicy_root)/src" 
use_fincludes= $(use_includes)
use_stamps= $(fflare_stamps)  $(AspPolicy_stamps) 
use_cflags=  $(fflare_cflags)  $(AspPolicy_cflags) 
use_pp_cflags=  $(fflare_pp_cflags)  $(AspPolicy_pp_cflags) 
use_cppflags=  $(fflare_cppflags)  $(AspPolicy_cppflags) 
use_pp_cppflags=  $(fflare_pp_cppflags)  $(AspPolicy_pp_cppflags) 
use_fflags=  $(fflare_fflags)  $(AspPolicy_fflags) 
use_pp_fflags=  $(fflare_pp_fflags)  $(AspPolicy_pp_fflags) 
use_linkopts= $(cmt_installarea_linkopts)   $(fflare_linkopts)  $(AspPolicy_linkopts) 
use_libraries= $(AspPolicy_libraries) 
includes= $(ppcmd)"$(srcdir)" $(use_includes)
fincludes= $(includes)
constituents= wrappers 
all_constituents= $(constituents)
constituentsclean= wrappersclean 
all_constituentsclean= $(constituentsclean)
cmt_installarea_paths=$(cmt_installarea_prefix)/$(tag)/bin $(cmt_installarea_prefix)/$(tag)/lib $(cmt_installarea_prefix)/share/lib $(cmt_installarea_prefix)/share/bin
Project4_installarea_prefix=$(cmt_installarea_prefix)
Project4_installarea_prefix_remove=$(Project4_installarea_prefix)
LD_LIBRARY_PATH=/data41/users/tosti/glast/InstallArea/rh9_gcc32/lib:/data45/software/ScienceTools/v8r0p4/InstallArea/rh9_gcc32/lib:/data41/users/tosti/users/tosti/InstallArea/rh9_gcc32/lib:/data41/users/tosti/glast/users/tosti/InstallArea/rh9_gcc32/lib:/data45/software/GlastExternals/cfitsio/v2470/lib:/data45/software/GlastExternals/fftw/3.0.1/lib:/data45/software/XMMSAS/xmmsas_20050815_1803/libsys:/data45/software/XMMSAS/xmmsas_20050815_1803/libextra:/data45/software/XMMSAS/xmmsas_20050815_1803/lib:/data45/software/heasoft/i686-pc-linux-gnu-libc2.2.4/lib:/data45/software/GlastExternals/cfitsio/v2470/lib:/data45/software/GlastExternals/fftw/3.0.1/lib:/opt/lcg/lib:/opt/globus/lib:/opt/edg/lib:/usr/local/lib:/opt/glite/lib:/opt/glite/externals/lib:/opt/d-cache/dcap/lib:/data45/software/lib:/data45/software/GlastExternals/cfitsio/v2470/lib:/data45/software/GlastExternals/fftw/3.0.1/lib:/data45/software/GlastExternals/pil/2.0.1/lib:/data45/software/GlastExternals/cfitsio/v3006/lib:/data45/software/GlastExternals/ROOT/v5.14.00d/root/lib:/data45/software/XMMSAS/xmmsas_20050815_1803/lib:/data45/software/XMMSAS/xmmsas_20050815_1803/libextra:/data45/software/star/lib
Project3_installarea_prefix=$(cmt_installarea_prefix)
Project3_installarea_prefix_remove=$(Project3_installarea_prefix)
Project2_installarea_prefix=$(cmt_installarea_prefix)
Project2_installarea_prefix_remove=$(Project2_installarea_prefix)
Project1_installarea_prefix=$(cmt_installarea_prefix)
Project1_installarea_prefix_remove=$(Project1_installarea_prefix)
cmt_installarea_linkopts= -L/data41/users/tosti/glast/$(Project1_installarea_prefix)/$(tag)/lib  -L/data45/software/ScienceTools/v8r0p4/$(Project2_installarea_prefix)/$(tag)/lib  -L/data41/users/tosti/users/tosti/$(Project3_installarea_prefix)/$(tag)/lib  -L/data41/users/tosti/glast/users/tosti/$(Project4_installarea_prefix)/$(tag)/lib 
