# -*- python -*-
# @file SConscript
# @brief scons build specifications for AspHealPix
#
# $Header$
# Authors: J. Chiang <jchiang@slac.stanford.edu>
# Version: asp_pgwave-01-10-00

import os
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()
swigEnv = baseEnv.Clone()
