# -*- python -*-
# @file SConscript
# @brief scons build specifications for AspHealPix
#
# $Header$
# Authors: J. Chiang <jchiang@slac.stanford.edu>
# Version: AspHealPix-00-00-03

import os
Import('baseEnv')
Import('listFiles')

libEnv = baseEnv.Clone()
swigEnv = baseEnv.Clone()

libEnv.Tool('AspHealPixLib', depsOnly = 1)
AspHealPixLib = libEnv.SharedLibrary('AspHealPix',
                                     listFiles(['src/*.cxx']))

swigEnv.Tool('AspHealPixLib')
lib_AspHealPix = swigEnv.SwigLibrary('_AspHealPix', 'src/AspHealPix.i')

swigEnv.Tool('registerTargets', package='AspHealPix',
             libraryCxts=[[AspHealPixLib, libEnv]],
             swigLibraryCxts=[[lib_AspHealPix, swigEnv]],
             includes=listFiles(['AspHealPix/*.h']),
             python=['src/AspHealPix.py'])
