# -*- python -*-
# @file SConscript
# @brief scons build specifications for BayesianBlocks
#
# $Header$
# Authors: J. Chiang <jchiang@slac.stanford.edu>
# Version: BayesianBlocks-02-00-01

import os
Import('baseEnv')
Import('listFiles')
libEnv = baseEnv.Clone()
swigEnv = baseEnv.Clone()

libEnv.Tool('BayesianBlocksLib', depsOnly = 1)
BayesianBlocksLib = libEnv.SharedLibrary('BayesianBlocks' ,
                                         ['src/Exposure.cxx','src/BayesianBlocks.cxx'])

swigEnv.Tool('BayesianBlocksLib')
lib_BayesianBlocks = swigEnv.SwigLibrary('_BayesianBlocks', 'src/BayesianBlocks.i')


swigEnv.Tool('registerTargets', package="BayesianBlocks",
             libraryCxts=[[BayesianBlocksLib, libEnv]],
             swigLibraryCxts=[[lib_BayesianBlocks, swigEnv]],
             includes=listFiles(['BayesianBlocks/*.h']),
             data = listFiles(['data/*']),
             python=['src/BayesianBlocks.py'])

# What about files in python directory?  Should they be installed?
# test_BayesianBlocks.py uses data/events.dat.  If test_BayesianBLocks.py
# is installed, this file must also be installed.  Recommend that
# name events.dat be changed to, e.g., BayesianBlocks_events.dat

