# -*- python -*-
# @file SConscript
# @brief scons build specifications for AspLauncher
#
# $Header$
# Authors: J. Chiang <jchiang@slac.stanford.edu>
# Version: AspLauncher-02-00-00

import os
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()

progEnv.Tool('registerTargets', package='AspLauncher',
             wrappedPython=listFiles(['python/*.py']) )

