# -*- python -*-
# @file SConscript
# @brief scons build specifications for AspLauncher
#
# $Header$
# Authors: J. Chiang <jchiang@slac.stanford.edu>
# Version: AspLauncher-01-04-00

import os
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()
swigEnv = baseEnv.Clone()
