# -*- python -*-
# @file SConscript
# @brief scons build specifications for asp_skymaps
#
# $Header$
# Authors: J. Chiang <jchiang@slac.stanford.edu>
# Version: asp_skymaps-01-13-02
import os
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()
swigEnv = baseEnv.Clone()

progEnv.Tool('asp_skymapsLib')
test_healpix = progEnv.Program('test_skymaps', listFiles(['src/test/*.cxx']))

libEnv.Tool('asp_skymapsLib', depsOnly = 1)
skymapsLib = libEnv.SharedLibrary('asp_skymaps', listFiles(['src/*.cxx']))

swigEnv.Tool('asp_skymapsLib')

#Try commenting out next line in hopes we don't need it
####swigEnv.Append(RPATH = swigEnv['LIBDIR'])
pySkymapsLib = swigEnv.SwigLibrary('_asp_skymaps','python/swig_setup.i')

progEnv.Tool('registerTargets', 
             package = 'asp_skymaps', 
             includes = listFiles(['skymaps/*.h']),
             topInclude = 'skymaps',
             libraryCxts = [[skymapsLib, libEnv]],
             swigLibraryCxts = [[pySkymapsLib, swigEnv]],
             data = listFiles(['data/*']),
             python = ['python/skymaps.py']
             )

