# -*- python -*-
# @file SConscript
# @brief scons build specifications for asp_skymaps
#
# $Header$
# Authors: J. Chiang <jchiang@slac.stanford.edu>
# Version: asp_skymaps-01-13-01
import os
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()
swigEnv = baseEnv.Clone()

progEnv.Tool('skymapsLib')
test_healpix = progEnv.Program('test_skymaps', listFiles(['src/test/*.cxx']))

libEnv.Tool('skymapsLib', depsOnly = 1)
skymapsLib = libEnv.SharedLibrary('skymaps', listFiles(['src/*.cxx']))

swigEnv.Tool('skymapsLib')
swigEnv.Replace(SHLIBPREFIX = '_')
#swigEnv.Replace(SHLIBSUFFIX = '.pyd')
swigEnv.Append(RPATH = swigEnv['LIBDIR'])
pySkymapsLib = swigEnv.SwigLibrary('skymaps','python/swig_setup.i')

progEnv.Tool('registerTargets', 
             package = 'skymaps', 
             includes = listFiles(['skymaps/*.h']),
             libraryCxts = [[skymapsLib, libEnv]],
             swigLibraryCxts = [[pySkymapsLib, swigEnv]],
             python = ['python/skymaps.py']
             )

