# -*- python -*-
# @file SConscript
# @brief scons build specifications for pyASP
#
# $Header$
# Authors: J. Chiang <jchiang@slac.stanford.edu>
# Version: pyASP-03-06-02

import os
Import('baseEnv')
Import('listFiles')
progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()
swigEnv = baseEnv.Clone()
