# -*- python -*-
# @file SConscript
# @brief scons build specifications for pyASP
#
# $Header$
# Authors: J. Chiang <jchiang@slac.stanford.edu>
# Version: pyASP-03-06-02

import os
Import('baseEnv')
Import('listFiles')

libEnv = baseEnv.Clone()
swigEnv = baseEnv.Clone()
libEnv.Tool('pyASPLib', depsOnly=1)
pyASPLib = libEnv.SharedLibrary('pyASP', listFiles(['src/*.cxx']))

swigEnv.Tool('pyASPLib')
                                
lib_pyASP = swigEnv.SwigLibrary('_pyASP','src/pyASP.i')

swigEnv.Tool('registerTargets', package='pyASP',
             libraryCxts=[[pyASPLib, libEnv]],
             swigLibraryCxts=[[lib_pyASP, swigEnv]],
             includes=listFiles(['pyASP/*.h']),
             data = listFiles(['data/*']),
             python=['src/pyASP.py'])

# pyASP has many other files in the python directory.  Do any
# need to be installed?
